# Generated by Django 3.2.6 on 2021-10-02 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211001_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='liker', to=settings.AUTH_USER_MODEL),
        ),
    ]
